# Generated by Django 3.0.7 on 2020-07-17 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200717_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='link',
            new_name='webinfo',
        ),
    ]
